### ISSUE TITLE
Error with empty message

### ISSUE THREAD

**Issue by N1ghtF1re** [Lemba-Anastasia/WebConsoleChat#3]
If the console client sends a blank message, an error occurs.

```
Exception in thread "Thread-10" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at com.example.sweater.consoleServer.MonoThreadClientHandler.run(MonoThreadClientHandler.java:36)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by N1ghtF1re** [comment]
https://github.com/Lemba-Anastasia/WebConsoleChat/blob/72e3c5eba19acaa8ad7faa9014f33d33b12e622f/src/main/java/com/example/sweater/consoleServer/MonoThreadClientHandler.java#L36

And here is the reason

**Comment by N1ghtF1re** [comment]
https://github.com/Lemba-Anastasia/WebConsoleChat/pull/4
